### ISSUE TITLE
ErrorException: Class 'Tachyon' not found

### ISSUE THREAD

**Issue by smeedijzer-internet** [humanmade/smart-media#113]
Hi,

I get an error: Class 'Tachyon' not found in file:
 [...]plugins/smart-media/inc/cropper/namespace.php on line 844

```
    $images = Tachyon::parse_images_from_html( $content );
    if ( empty( $images ) ) {
        // No images, leave early.
        return $content;
    }
```

'Some features in this plugin will work on their own however some are designed to augment the existing tools we use such as Tachyon.'

I try to use Smart Media as a stand-alone plugin (I really like the crop option!). Is it possible to make this work?

**Comment by roborourke** [comment]
Oh that should have a `function_exists()` check, sorry about that. Unfortunately right now it's really difficult to support the UI as it is without Tachyon. It's not really on the roadmap for us right now as we have a ton of things that are higher priority but I'm open to contributions to making it work without Tachyon.

**Comment by smeedijzer-internet** [comment]
Thanks for clearing that up! I wil check for other solutions

**Comment by roborourke** [comment]
Going to close this out, it's going ot be some time before we reach a point we can rewrite this to be Tachyon agnostic but the plan is to make the image resizing service more plug and play, eg. you could Photon or Cloudinary for example.
