### ISSUE TITLE
BUG: Adding/editing a crop does not work in media modal

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/smart-media#119]
Steps to reproduce:
1. Create a new post
2. Add an image block
3. Upload a new image or select an image from the Media Library
4. Select a size
5. No cropping controls appear on the page, no ability to drag, clicking the crop icon makes the entire image go dark and adds a button that says "Remove custom crop" with no apparent area visible

No errors in the browser console.

Screen recording of issue: https://i.imgur.com/Wky0cM3.gif

https://github.com/humanmade/product-dev/issues/602

**Comment by roborourke** [comment]
This appears to be related to the jQuery upgrade, however even with the `jquery-migrate` script it still isn't behaving. Might take a while to resolve this as worst case we'll have to replace the `imgareaselect` cropper library wholesale.
