### ISSUE TITLE
Possible BUG: Cannot crop image in the block editor as an author

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/smart-media#120]
This may be a permissions issue. However, if it is, the error message that displays is non-specific and, if possible, it might be good to update the error message to make it clear that the current user isn't allowed to edit the image crop rather than not being allowed to edit "this post" (which they are obviously currently doing).

Steps to reproduce:
1. Sign in as an author
2. Create a new post
3. Add an image block
4. Upload an image or select one from the Media Library
5. Attempt to use the crop tool in the block editor.
6. You will get an error at the bottom of the page which says "Could not edit image. Sorry, you are not allowed to edit this post."
7. The image does not reflect the cropped value

Screen recording of bug: https://i.imgur.com/bsVMn24.gif

**Comment by jazzsequence** [comment]
The thing that stands out the most here is that the error message is confusing or appears to be inaccurate.

https://github.com/humanmade/product-dev/issues/602

**Comment by PriyaBhatia0210** [comment]
Also this, no crop handles seen

![Image crop](https://user-images.githubusercontent.com/55112796/104650095-b27a5c00-5683-11eb-8673-13c695170e6b.gif)

**Comment by jazzsequence** [comment]
@PriyaBhatia0210 for the inline crop that's part of the Gutenberg image block, there are no crop handles. The UX is super weird and really hard to show with the example that you have, since it's such a small image, but the idea is that you use _zoom_ controls to zoom in and drag to move to the area you want to crop. 

https://i.imgur.com/TTsTomg.gif

**Comment by PriyaBhatia0210** [comment]
Gotcha @jazzsequence. That worked for me. Thanks!

**Comment by roborourke** [comment]
I'm not sure this is actually smart-media specific. Does it work as expected with this plugin turned off?

**Comment by roborourke** [comment]
I couldn't replicate this locally but I can on platform test. I think it's actually expected behaviour as author's can only edit their own posts so you can't crop an image someone else uploaded but you can crop your own. This is just WP behaviour rather smart media or Altis specific so closing this out.
