### ISSUE TITLE
Clicking image in featured image selection opens the modal in library view

### ISSUE THREAD

**Issue by roborourke** [humanmade/smart-media#127]
Once a featured image has been selected, saved and then page refreshed, clicking on the featured image itself will open the media modal in the library view rather than having the featured image selected.

This is a bit confusing because before a page refresh the media modal state is what you would expect.

Reported by @abhishek-kaushik

**Comment by roborourke** [comment]
This issue actually persists in WP versions < 5.6. Must be some difference in how Gutenberg handles the featured image settings.

**Comment by miteshpandey** [comment]
@roborourke: We've tested this on Altis v7, and it doesn't seem to work. Any suggestions?

**Comment by roborourke** [comment]
Hi @miteshpandey, can you confirm which version of smart media is running? You can find it under the Altis Logo menu dropdown in the admin bar, go to the "About" page, then the "Credits" tab and look for `humanmade/smart-media`

**Comment by miteshpandey** [comment]
@roborourke : `humanmade/smart-media (0.3.9)`

**Comment by roborourke** [comment]
@miteshpandey if this a priority for your project ideally someone on the team can take a look into it. In terms of Altis development this isn't super high in terms of priority in the backlog currently.

**Comment by miteshpandey** [comment]
Thanks @roborourke 
Yes, it's a very high priority at the moment. There's a feature which is getting affected by this issue. As informed to us previously, we were under the impression that updating to Altis v6 will resolve this. However, we updated straight to v7 from v5 (due to some business decisions) and don't see this resolved on its own. Client is waiting for this to be resolved asap. 
Thanks for your help :)

**Comment by roborourke** [comment]
@miteshpandey are you able to expand more on the feature getting affected by it? Is there some project code interacting with the media modal too?

**Comment by miteshpandey** [comment]
@roborourke : I believe reviewing this PR will help - https://github.com/humanmade/fujitv/pull/580
For more technicality, I'll ask the engineer on the project @skswong8 to get in touch tomorrow (he's afk now).

**Comment by miteshpandey** [comment]
@roborourke: Do you need any more assistance? Are we able to prioritise this on high priority?

**Comment by showw** [comment]
Clients are very keen to see this problem solved, and say it is the most important reason they use Altis7.
Addressing this issue will be a great help to our project.
Thank you for your help.
@roborourke

**Comment by rmccue** [comment]
@miteshpandey Please keep any client-specific conversations to Slack, this is not the place to have these discussions.

**Comment by roborourke** [comment]
This bug was fixed but still occurs due to an incompatibility with the Google AMP plugin. Fixed by #158

**Comment by roborourke** [comment]
The compatibility issue was fixed in this plugin so closing out again.
