### ISSUE TITLE
Custom crops don't get rendered in the editor

### ISSUE THREAD

**Issue by goldenapples** [humanmade/smart-media#19]
If you select a custom crop for an image through the Cropper modal controls, it doesn't render in the editor.

For example, after applying the patch from https://github.com/humanmade/smart-media/pull/18,  I tried to crop this image to a 5:4 crop focused on the people in it:

<img width="1135" alt="Screen Shot 2019-08-27 at 3 37 53 PM" src="https://user-images.githubusercontent.com/665992/63802608-fc24a400-c8e0-11e9-94ca-a5e1750c4a4b.png">

The correct dimensions are applied, and it renders correctly on the front end:

<img width="1658" alt="Screen Shot 2019-08-27 at 3 37 22 PM" src="https://user-images.githubusercontent.com/665992/63802580-ef07b500-c8e0-11e9-94df-6dac91a683f2.png">

... but in the editor a default crop is still being displayed:

<img width="1484" alt="Screen Shot 2019-08-27 at 3 38 11 PM" src="https://user-images.githubusercontent.com/665992/63802489-bf58ad00-c8e0-11e9-9c27-9748d5487544.png">

In order for the editor preview to be useful, we should be able to show the actual crop which is being used for each image block.

This crop is controlled by the `media_details.sizes[].source_url` field in the REST API response for `wp/v2/media/{id}`.

**Comment by roborourke** [comment]
Working on this in #20

**Comment by goldenapples** [comment]
Seems to be fixed by #20, nice!
