### ISSUE TITLE
Use Tachyon for Core's "Big Image" feature.

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/smart-media#31]
I'm not sure if this is best placed here or in the Tachyon Plugin, feel free to move.

In [wp-47873](https://core.trac.wordpress.org/ticket/47873) scaling down of large images was introduced to reduce the incidents of billion pixel wide images being displayed on much smaller screens. Additional details are provided in an [image handling](https://make.wordpress.org/core/2019/10/11/updates-to-image-processing-in-wordpress-5-3/) make post.

It would be handy to replace this feature with Tachyon.

The core feature can be disabled with:

```php
<?php
apply_filters( 'big_image_size_threshold', '__return_false' );
```

However, I'd suggest the following approach:
```php
<?php
function sm_media_return_false() {
    return false;
}
add_filter( 'big_image_size_threshold', 'sm_media_return_false', 100 );

function sm_full_attachment_image_src( $image, $attachment_id, $size ) {
    if ( $size !== 'full' ) {
        return $image;
    }

    // Get native dimension, original file.

    remove_filter( 'big_image_size_threshold', 'smart_media_return_false', 100 );
    $threshold = (int) apply_filters(
        'big_image_size_threshold',
        2560,
        [$native_width, $native_height],
        $original_file,
        $attachment_id
    );
    add_filter( 'big_image_size_threshold', 'smart_media_return_false', 100 );

    // resize image if required.
    return $image
}
add_filter( 'wp_get_attachment_image_src', 'sm_full_attachment_image_src', 10, 3 );
```

But with namespaces, etc, etc ;)

**Comment by roborourke** [comment]
I've intentionally avoided this - having a smaller image to generate the resized thumbs from makes Tachyon quicker and avoids memory issues when running it. The resulting images are still generated from a large high quality one so I'm not planning on supporting this here. Happy to discuss further but I'm going to close this out to keep focus on some bugs / enhancements I need to do.
