### ISSUE TITLE
option to disable tachyon integration

### ISSUE THREAD

**Issue by jshwlkr** [humanmade/smart-media#35]
I wouldn't hate having a filter to disable Tachyon integration (and whatever UI corresponds to it's features). I know it's probably a big part of this plugin, but given the opportunity I'd like to offer some of the more cosmetic enhancements to some users without having to commit to Tachyon.

**Comment by roborourke** [comment]
Hey @jshwlkr. Unfortunately the bulk of it is tied to Tachyon, or at least some sort of image resizing service. It'd technically work with Jetpack / Photon for instance. This is required for the cropping UI which is the main feature.

If you just want the alternative styling for the image widths you could pull out the CSS for that. Perhaps not worth using the full plugin just for that bit.

I don't really see us doing this to be honest, it's more likely we'd look at allowing the use of other image resizing services instead like Cloudinary / Photon.
