### ISSUE TITLE
An image cannot be selected until Change Image is clicked

### ISSUE THREAD

**Issue by igmoweb** [humanmade/smart-media#36]
Steps to reproduce:

1. Insert an image block and open the media manager
2. Click on any image
3. Once the left panel with the different images is displayed, click on the `Select` button.
4. Nothing happens even if this button is clicked several times.
5. Click on `Change image`.
6. Select the same image again. Now it can be inserted.

When an image is clicked, there's an output error in the JS console. Here's a little GIF that shows it (it's big for GitHub so I'm uploading it to Drive: https://drive.google.com/file/d/1LWQIv5uvyzuaxFRWGI0SsKALCx35HeP8/view)

It seems that the error starts on `cropper.js:183` but triggered in `media-views`:

```js
 sidebar.set( 'details', new Media.view.Attachment.Details( {
      controller: this.controller,
      model: single,
      priority: 80
    } ) );
```
`this.controller` is `undefined` when the image is clicked for the first time yet I'm not 100% sure if that's what is causing the problem when the image is selected but I hope it helps to discover it.

**Comment by roborourke** [comment]
This could be because the image hasn't changed if it's an existing image or I'm not setting a default selection at this point some how.

Will spend some time on this today, thanks for the report!
