### ISSUE TITLE
Image cropper not applying size selection to image blocks

### ISSUE THREAD

**Issue by igmoweb** [humanmade/smart-media#37]
It seems that the image cropper is not working anymore in 3.0 but it could be related to #36 

**How to reproduce**

1. Add an image block and click on _Media Library_
2. Select an image but then click on `Change Image`. Due to #36, you need to do that in order to reproduce this issue.
3. Select now **a different image**.
4. Click on a size on the left side that allows to crop the image and change the cropping area.
5. Select the image and see the results. The selected size is not applied to the block.

**Note**: While writing this I realized that the _Image Size_ selector in the block sidebar does not change when an image is selected. If you try to switch it, the size will change. Maybe the problem is that the image size attribute is not updated when the image is selected. Here's a GIF with the whole process.

![Kapture 2020-02-18 at 11 05 50](https://user-images.githubusercontent.com/1516569/74725822-b832ac00-523e-11ea-9ac1-9e604278cf13.gif)

**Comment by roborourke** [comment]
This has been the case with Gutenberg from the outset unfortunately - I think the confusion is that with the cropping UI you can select image sizes from the left and select the image without having to go back to the media library view first. The cropping UI isn't really selecting the image size to insert but that's particularly intuitive!

I think the answer here will be down what's possible in terms of Gutenberg interactions:

* Find a way to set the size dropdown according to selection in cropper
* Change the select button in the cropper to return you to the media library, then the workflow is back to default WP

**Comment by roborourke** [comment]
FYI I updated the (very threadbare!) docs on the readme of this repo - we now have hooks to integrate blocks with the image size selection in the cropping UI. Only `core/image` is supported by default so far - thanks for the prompt to get this sorted.
