### ISSUE TITLE
Update filters used for making images responsive for WP 5.5

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/smart-media#49]
WordPress 5.5 will replace the `wp_make_content_images_responsive` with the generic function `wp_filter_content_tags` that will add the `load=lazy` attribute to images alongside making them responsive by adding the `srcset` and `sizes` attributes.

As this plugin replaces the function, it wil need to be updated to account for the renamed function.

Refer to the [change set](https://core.trac.wordpress.org/changeset/47554) and the related ticket [#44427](https://core.trac.wordpress.org/ticket/44427)

**Comment by roborourke** [comment]
Grrr. Same in the Tachyon Plugin too then, cheers for the heads up!

**Comment by peterwilsoncc** [comment]
Just noticed I made a typo in the description. It should WordPress 5.4. 

Rob, you probably figured that out but noting for the purpose of clarity.

**Comment by roborourke** [comment]
Seems this got punted to 5.5 after all, updating the title.
