### ISSUE TITLE
SVGs in Media popup don't display

### ISSUE THREAD

**Issue by joehoyle** [humanmade/smart-media#58]
It seems the `width: auto` etc CSS we are setting on `img` in the smart media modal doesn't work with SVG images, see

![](https://joehoyle-captured.s3.amazonaws.com/Screen-Shot-2020-05-06-15-56-41.56-lgavBtmWmAHuP1MIAP7VVnJvh6Llh1or6Kp9iG067YKNDaOkXaeWqGx3A3UvjalINQCe6jcMj5MUMywEbxim6UCfkbiS7DgYK2mp.png)

**Comment by roborourke** [comment]
What, must've been a regression somewhere, they certainly used to. Possibly a daft question but the SVG image isn't white is it?
