### ISSUE TITLE
Failing to upload images via the media manager modal

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/smart-media#6]
<img width="1648" alt="screen shot 2018-11-13 at 17 39 57" src="https://user-images.githubusercontent.com/907521/48432026-2e5a8000-e76b-11e8-9422-ce0ae0794bb5.png">

**Comment by roborourke** [comment]
Going to close this out as it's unclear what action to take and doesn't seem to be coming much any more, if at all.

Can always be reopened at a later date if we find a way to reproduce it.
