### ISSUE TITLE
Smart media trying to parse metadata of posts, not just attachments

### ISSUE THREAD

**Issue by stuartshields** [humanmade/smart-media#63]
The Attachment ID `115072` has been deleted, however cropper is attempting to retrieve the meta data for the attachment:
```
22 hours ago
Warning[08-Jun-2020 10:58:41 UTC] PHP Warning:  Could not retrieve image meta data for Attachment ID "115072" in /usr/src/app/vendor/humanmade/smart-media/inc/cropper/namespace.php on line 886
```

Another odd thing is `115029` is a post, however cropper is also attempting to retrieve meta data (Post exists in this case):
```
22 hours ago
Warning[08-Jun-2020 10:58:36 UTC] PHP Warning:  Could not retrieve image meta data for Attachment ID "115029" in /usr/src/app/vendor/humanmade/smart-media/inc/cropper/namespace.php on line 886
```

**Comment by roborourke** [comment]
That's kinda wild, pretty sure it does a check to see if it's an attachment first but perhaps there's an image tag referencing an incorrect ID. Cheers for the report. Any chance you have a full stack trace to help pinpoint the problem further?

**Comment by stuartshields** [comment]
@roborourke let's reconnect when you are online tonight to discuss this further.
