### ISSUE TITLE
Media Library Button are inactive after uploading new featured Image

### ISSUE THREAD

**Issue by abhishek-kaushik** [humanmade/smart-media#78]
Steps to reproduce:

1. Upload new image for featured image.
2. select the image as featured image.
3. open the featured image media view.
![Skadoosh 2020-08-17 at 14 31 40](https://user-images.githubusercontent.com/1883835/90377982-6c9a7700-e096-11ea-9f37-95b30e116bed.png)

**Comment by roborourke** [comment]
@abhishek-kaushik can you confirm the version of smart media you're seeing this with?

**Comment by roborourke** [comment]
Also could you perhaps provide a gif to demonstrate this? There might be some nuance in the path taken through the media modal.

**Comment by abhishek-kaushik** [comment]
![Skadoosh 2020-08-24 at 18 59 49](https://user-images.githubusercontent.com/1883835/91050477-52cfd580-e63c-11ea-93dd-9e8cba2566c8.gif)

@roborourke here you go. I tested this on `platform-test`

**Comment by roborourke** [comment]
@abhishek-kaushik I think this is fixed now. Are you able to confirm that for me?

**Comment by lachlanj** [comment]
@roborourke this is fixed me me now. I can't replicate the bug anymore so I think you are ok to close this one out.

Thanks for your help on this!

**Comment by roborourke** [comment]
Sweet. Think it's time for a v1.0.0 stable release 👍
