### ISSUE TITLE
Clicking on the image and cropping making the media position to zero

### ISSUE THREAD

**Issue by abhishek-kaushik** [humanmade/smart-media#79]
steps reproduce.
1. go to cropping tool
2. just click on the image.
3. click on the crop button
![cropper](https://user-images.githubusercontent.com/1883835/90399326-67e6ba80-e0b8-11ea-8bc8-41dff887ac52.gif)

**Comment by roborourke** [comment]
This seems to be some issue with the UI responding quite slowly. I'll see if the cropping UI can be frozen until the changes are saved.
