### ISSUE TITLE
Media API does not Return Cropped Image sizes

### ISSUE THREAD

**Issue by abhishek-kaushik** [humanmade/smart-media#81]
Steps to reproduce:
1. Crop an image
2. look for the WP Media API for that attachment.
3. Under Media details Image sizes are still `crop_strategy=smart` not `crop` dimensions.

**Comment by roborourke** [comment]
@abhishek-kaushik I can't really fix this one easily - using that URL will give you a consistent result from Tachyon. What's the use-case you need the exact dimensions for?

**Comment by abhishek-kaushik** [comment]
@roborourke , we are using post API with `embed` to get post details including featured_image so for that we need the crop dimensions for the images.

**Comment by abhishek-kaushik** [comment]
This is the result we are getting
```
"landscape_wide": {
        "width": 1536,
        "height": 864,
        "file": "4f3ac9f4ccc1d80261c98d34c00d5f02-c42c257f2-1536x864.jpg",
        "mime_type": "image/jpeg",
        "source_url": "https://fujitv.altis.dev/tachyon/2020/08/4f3ac9f4ccc1d80261c98d34c00d5f02.jpg?resize=1536,864&crop_strategy=smart",
        "crop": {
          "x": 0,
          "y": 0,
          "width": 2544,
          "height": 1431
        }
      }
```

once we remove the filter https://github.com/humanmade/smart-media/blob/master/inc/cropper/namespace.php#L23

```"landscape_wide": {
        "_tachyon_dynamic": true,
        "width": 1536,
        "height": 864,
        "file": "4f3ac9f4ccc1d80261c98d34c00d5f02-c42c257f2-1536x864.jpg",
        "mime_type": "image/jpeg",
        "source_url": "https://fujitv.altis.dev/tachyon/2020/08/4f3ac9f4ccc1d80261c98d34c00d5f02.jpg?resize=1536,864&crop=0px,0px,2544px,1431px"
      }
```
