### ISSUE TITLE
Customize Header Control not saving selection

### ISSUE THREAD

**Issue by goldenapples** [humanmade/smart-media#88]
When using the Header Image customizer control on a WordPress 5.4.2 site with Smart Media enabled, selecting a new header image closes the modal without switching to the cropper frame as is expected. As a result, it's not possible to update the header image through the customizer. 

I'm just opening this ticket to track the issue; will come back to troubleshoot and add details later today when I have the chance.

**Comment by roborourke** [comment]
Thanks Than, this was a recent regression when I refactored some of the code - I forgot to copy across the check for whether the media modal had the 'cropper' state available first before binding our own.
