### ISSUE TITLE
Remove hardcoding of Tachyon ?fit=x on Original Image in smart media

### ISSUE THREAD

**Issue by stuartshields** [humanmade/smart-media#93]
@roborourke so currently on the secure media stuff I'm working on, the Original image doesn't load in the Media Modal:

![Screen Shot 2020-09-07 at 11 20 40 am](https://user-images.githubusercontent.com/15369210/92340033-2ddb6800-f0fc-11ea-81eb-4a592ce0749e.png)

This is because we are adding in duplicate `?` to the original URL:
```
https://platform.altis.dev/tachyon/2020/09/50304770521_8c5519f111_o-1.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20200907%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200907T012030Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21600&X-Amz-Signature=25a34e7b426a723f1ce54a9f1c62f51c1b734a1fbf091964d011a20ea8e9dd4e?fit=0,120
```

The cause is `?fit=0,120` being hardcoded https://github.com/humanmade/smart-media/blob/master/inc/cropper/media-template.php#L173 

As soon as you remove `?fit=0,120` the URL loads as it should.

**Comment by roborourke** [comment]
I won’t remove It but will make sure it checks the URL for an existing query string and switch to ampersand. Cheers for letting me know

**Comment by stuartshields** [comment]
@roborourke makes sense to check the URL for an existing string. We have pushed secure media launch to next week, so let me know when I can test the fix for this to see if it resolves the issue.

Thanks again.
